name: Build next-prod
on:
  push:
    branches:
      - next-prod
jobs:
  prod-push:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set time zone to Europe/Helsinki
        uses: zcong1993/setup-timezone@master
        with:
          timezone: "Europe/Helsinki"
      - name: Push next image as next-prod
        run: ./.github/workflows/scripts/push_prod.sh
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_AUTH: ${{ secrets.DOCKER_AUTH }}
          DOCKER_BASE_TAG: next-prod
          DOCKER_DEV_TAG: next
