name: Build prod from release
on:
  release:
    types:
      - published
jobs:
  prod-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${GITHUB_REF##*/} =~ ^202[0-9][0-1][0-9][0-3][0-9] ]]; then
              echo "match=true" >> $GITHUB_OUTPUT
          fi
      - name: Push latest image as v3-prod
        if: steps.check-tag.outputs.match == 'true'
        run: ./.github/workflows/scripts/push_prod.sh
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_AUTH: ${{ secrets.DOCKER_AUTH }}
          DOCKER_BASE_TAG: v3-prod
          DOCKER_DEV_TAG: v3
