name: Deploy v3-dev
on:
  push:
    branches:
      - v3
jobs:
  docker-push:
    if: github.ref == 'refs/heads/v3'
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set time zone to Europe/Helsinki
        uses: zcong1993/setup-timezone@master
        with:
          timezone: "Europe/Helsinki"

      - name: configure Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: log in to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_AUTH }}

      - name: Cache .yarn/cache
        uses: actions/cache@v3
        with:
          path: '.yarn/cache'
          key: yarn-cache-${{ github.ref_name }}
          restore-keys: yarn-cache-v2

      - name: Create Docker image tag
        id: docker-tags
        run: |
          echo "::set-output name=permanent-tag::v3-dev-$(date +"%Y-%m-%dT%H.%M.%S")-${GITHUB_SHA:0:7}"

      - name: build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            hsldevcom/digitransit-ui:v3-dev
            hsldevcom/digitransit-ui:${{ steps.docker-tags.outputs.permanent-tag }}
          # https://github.com/docker/build-push-action/blob/9472e9021074a3cb3279ba431598b8836d40433f/docs/advanced/cache.md#github-cache
          # https://github.com/moby/buildkit#registry-push-image-and-cache-separately
          cache-from: type=gha
          cache-to: type=gha,mode=max,oci-mediatypes=true,compression=zstd
          push: true
